### ISSUE TITLE
[support]: ALCF: mvapich on Polaris

### ISSUE THREAD

**Issue by koysean** [E4S-Project/e4s#137]
### Name of Software

mvapich

### Contact Details

skoyama@anl.gov

### HPC System

ALCF

### Request Description

`mpirun` provided by mvapich on Polaris from module `e4s/22.08/mvapich2` cannot run any programs.

An MPI hello world program builds with the `mpicc` compiler but throws errors at runtime due to a series of `cannot open shared object file: No such file or directory.` errors upon `MPI_Init`. The libraries in question are `libibverbs.so`, `libibmad.so`, `libibumad.so`, and `librdmacm.so`.

### Relevant log output

```shell
Error opening libibverbs.so: libibverbs.so: cannot open shared object file: No such file or directory.
Please retry with MV2_LIBIBVERBS_PATH=<path/to/libibverbs.so>                                             
mv2_ibv_dlopen_init returned -1                                                                           
Error opening libibmad.so: libibmad.so: cannot open shared object file: No such file or directory.        
Please retry with MV2_LIBIBMAD_PATH=<path/to/libibmad.so>                                                 
mv2_mad_dlopen_init returned -1                                                                           
Error opening libibumad.so: libibumad.so: cannot open shared object file: No such file or directory.
Please retry with MV2_LIBIBUMAD_PATH=<path/to/libibumad.so>
mv2_umad_dlopen_init returned -1
Error opening librdmacm.so: librdmacm.so: cannot open shared object file: No such file or directory.
Please retry with MV2_LIBRDMACM_PATH=<path/to/librdmacm.so>
mv2_rdma_dlopen_init returned -1
[x3003c0s13b0n0:mpi_rank_0][MPIDI_CH3_Init] Failed to locate underlying libraries using dlopen. Please consider setting one of the suggested environment variables to the path of the missing library. Or please reconfigure after setting --disable-ibv-dlopen
Fatal error in MPI_Init:
Other MPI error, error stack:
MPIR_Init_thread(500): 
MPID_Init(623).......: channel initialization failed
MPIDI_CH3_Init(739)..: mv2_dlopen_init
(unknown)(): Other MPI error

[cli_0]: aborting job:
Fatal error in MPI_Init:
Other MPI error, error stack:
MPIR_Init_thread(500): 
MPID_Init(623).......: channel initialization failed
MPIDI_CH3_Init(739)..: mv2_dlopen_init
(unknown)(): Other MPI error
```

### Reproduce Bug

```bash
1. Starting from default environment, load the e4s/22.08/mvapich2 module
2. Compile program with mpicc or mpicxx
3. Run program with mpirun
```

**Comment by sameershende** [comment]
Hi @koysean ,
  I have built the latest mvapich 3.0rc version on Polaris using the cray libfabric (ofi). To try this:
`qsub -I -l select=2 -l filesystems=home:eagle -l walltime=1:00:00  -A <Project> -q debug
(2023-10-04/base) sameer@x3104c0s13b0n0:~/m> module use /soft/ecp/ParaTools/modulefiles
(2023-10-04/base) sameer@x3104c0s13b0n0:~/m> module load mvapich2

Lmod is automatically replacing "nvhpc/22.11" with "gcc/11.2.0".

(2023-10-04/base) sameer@x3104c0s13b0n0:~/m> which mpicc
/soft/ecp/ParaTools/opt/mvapich/plus/3.0rc/bin/mpicc
(2023-10-04/base) sameer@x3104c0s13b0n0:~/m> cat foo.c
#include "mpi.h"
#include <stdio.h>
int main(int argc, char *argv[])
{
    int rank, nprocs, len;
    char name[MPI_MAX_PROCESSOR_NAME];

    MPI_Init(&argc,&argv);
    MPI_Comm_size(MPI_COMM_WORLD,&nprocs);
    MPI_Comm_rank(MPI_COMM_WORLD,&rank);
    MPI_Get_processor_name(name, &len);
    printf("Hello, world.  I am %d of %d on %s\n", rank, nprocs, name);fflush(stdout);
    MPI_Finalize();
    return 0;
}
(2023-10-04/base) sameer@x3104c0s13b0n0:~/m> mpicc foo.c -o foo
(2023-10-04/base) sameer@x3104c0s13b0n0:~/m> mpirun -np 2 ./foo
Warning: Permanently added 'x3104c0s1b0n0.hsn.cm.polaris.alcf.anl.gov,10.201.4.27' (ECDSA) to the list of known hosts.
Hello, world.  I am 0 of 2 on x3104c0s13b0n0
Hello, world.  I am 1 of 2 on x3104c0s1b0n0
`

Would you please try this? If it works properly for you and you accept it, I will update the e4s/22.08 module. The problem was that the center had deleted NVHPC and CUDA 11.5 libraries that E4S' mvapich2 was built with in August 2022. The new library has been built with NVHPC 23.3 with CUDA 11.8 but if these libraries are deleted from the syst in the future, mvapich 3.0rc will stop working.

**Comment by koysean** [comment]
Hi Sameer, I'm able to confirm functionality. Please do update the e4s/22.08 module to use this new mvapich2. Thank you so much!

**Comment by sameershende** [comment]
Hi @koysean , 
 I have updated the e4s/22.08/mvapich2 module so it loads this mvapich2/3.0rc module. Here are my tests to confirm that it is using the new mvapich2:
 ```
(2023-10-04/base) sameer@polaris-login-04:~/m> qsub -I -l select=2 -l filesystems=home:eagle -l walltime=1:00:00  -A <ACCOUNT> -q debug
qsub: waiting for job 1179264.polaris-pbs-01.hsn.cm.polaris.alcf.anl.gov to start
qsub: job 1179264.polaris-pbs-01.hsn.cm.polaris.alcf.anl.gov ready

(2023-10-04/base) sameer@x3110c0s13b0n0:~> module list

Currently Loaded Modules:
  1) nvhpc/22.11        4) cray-mpich/8.1.25   7) cray-libpals/1.2.11  10) libfabric/1.15.2.0      13) craype-accel-nvidia80
  2) craype/2.7.20      5) cray-pmi/6.1.10     8) PrgEnv-nvhpc/8.3.3   11) craype-network-ofi
  3) cray-dsmml/0.2.2   6) cray-pals/1.2.11    9) craype-x86-rome      12) perftools-base/23.03.0

 

(2023-10-04/base) sameer@x3110c0s13b0n0:~> module load e4s/22.08/mvapich2

Lmod is automatically replacing "nvhpc/22.11" with "gcc/12.2.0".


Lmod is automatically replacing "PrgEnv-nvhpc/8.3.3" with "PrgEnv-gnu/8.3.3".

(2023-10-04/base) sameer@x3110c0s13b0n0:~> which mpicc
/soft/ecp/ParaTools/opt/mvapich/plus/3.0rc/bin/mpicc
(2023-10-04/base) sameer@x3110c0s13b0n0:~> cd m
(2023-10-04/base) sameer@x3110c0s13b0n0:~/m> mpicc foo.c -o foo
(2023-10-04/base) sameer@x3110c0s13b0n0:~/m> mpirun -np 2 ./foo
Warning: Permanently added 'x3110c0s13b0n0.hsn.cm.polaris.alcf.anl.gov,10.201.2.38' (ECDSA) to the list of known hosts.
Warning: Permanently added 'x3110c0s25b1n0.hsn.cm.polaris.alcf.anl.gov,10.201.2.21' (ECDSA) to the list of known hosts.
Hello, world.  I am 0 of 2 on x3110c0s13b0n0
Hello, world.  I am 1 of 2 on x3110c0s25b1n0
(2023-10-04/base) sameer@x3110c0s13b0n0:~/m> module list

Currently Loaded Modules:
  1) craype-x86-rome      4) perftools-base/23.03.0   7) cray-dsmml/0.2.2  10) cray-libpals/1.2.11            13) gcc/11.2.0
  2) libfabric/1.15.2.0   5) craype-accel-nvidia80    8) cray-pmi/6.1.10   11) PrgEnv-gnu/8.3.3               14) mvapich2/3.0rc
  3) craype-network-ofi   6) craype/2.7.20            9) cray-pals/1.2.11  12) cudatoolkit-standalone/11.8.0  15) e4s/22.08/mvapich2

 
```
