### ISSUE TITLE
tags based on new release format

### ISSUE THREAD

**Issue by shahzebsiddiqui** [E4S-Project/e4s#2]
Based on our discussion with Eugene we are going with the date format version so I would suggest you release tag in same format and delete the v1.1 tag https://github.com/E4S-Project/e4s/releases/tag/v1.1 because this doesn't make sense.

**Comment by eugeneswalker** [comment]
Yes, I think date format is the way to go. The `v1.1` tag has been removed. I can create the new tag as soon as we are ready to make this prototype release "official." When should we do this?

**Comment by eugeneswalker** [comment]
We are trying to better specify what is meant by an E4S release. I think the consensus among facility team representatives and Ryan Adamson was that we need to simultaneously specify:
* a Spack commit
* a set of versioned packages built <b>with the aformentioned Spack commit</b>

This repository had previously had a release tag of `v1.1` before we moved in this direction. We have been talking about doing date based releases. I *think* that is what @shahzebsiddiqui was referencing. At least that's the way I took it, and why I responded the way I did.

What do you think @maherou ?

**Comment by maherou** [comment]
I agree that semantic versioning such as X.Y does not make sense for E4S at this time, since there is no concept of minor version or backward compatibility that a minor release would imply.

At the same time, I am not a fan of date-based release numbers for software products.  It is too much information for most people who need to ID a particular version.  Can we simply use natural numbers?  We could call the coming release Version 2.

The release number would be tied to both the Spack commit and the set of versioned packages, which satisfies the requirements without forcing everyone who communicates about E4S to remember a long date tag.

**Comment by eugeneswalker** [comment]
> At the same time, I am not a fan of date-based release numbers for software products. It is too much information for most people who need to ID a particular version. Can we simply use natural numbers? We could call the coming release Version 2.

100% defer to the judgement of you and your colleagues. Happy to go whichever way you decide. One of the main reasons I put this up was to preview what the new release scheme might look like and elicit these types of discussions and suggestions.

**Comment by maherou** [comment]
Unless there is a strong practical reason to use a date ID, I like to keep things as simple as possible.  Let's plan on a natural number versioning scheme, unless someone else speaks up.

We are using the same versioning strategy for the E4S Community Policies.  Version 1 of the policies is almost through final approval.  BTW, the policy versioning does not have to sync with the E4S releases.

**Comment by shahzebsiddiqui** [comment]
[semver](https://semver.org/) doesn't make sense for e4s that's what we all thought initially. The date format would be useful if E4S plans to have regular release if we have commitment let's say once per quarter. If you want numbers like `e4s-1` `e4s-2` it doesn't mean much overtime when we have many versions. The date version scheme is used by intel, [schedmd](https://github.com/SchedMD/slurm/tags)

**Comment by maherou** [comment]
The schedmd approach could work.  Do you know if there is a de facto standard along these lines?  I would like to tap into an approach that is commonly used.  In the end, I want to do the right thing.  Thanks for the pointer.

**Comment by rmadamson** [comment]
Here is a defacto standard based on [calendar versioning](https://calver.org/).  @shahzebsiddiqui pointed me to Ubuntu's [release naming strategy](https://ubuntu.com/about/release-cycle).  It's based on the YY.MM in which it was released.  It seems that larger projects with broad scope fit better into a calendar version release scheme since clear features are harder to plan out when rolling major versions.  Personally, I think that our strategy should be a clue for users as to how we release tagged versions -- if we are planning on releasing quarterly, we should stick with calver.

**Comment by maherou** [comment]
I am fine with the YY.MM approach, given the precedents.
